name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: LaTeX compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        # The root LaTeX file to be compiled
        root_file: document.tex
        # Extra arguments to be passed to the latex compiler
        args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'document.pdf'
